= test blog
:published_at: 2015-02-11
:hp-tags: tag1,tag2,tag3
:hardbreaks:


Use ":" to define global attribute 




this is a test

Plus symbol is line break. Line 1 +
and Line 2


[%hardbreaks]
Line break attributes to...
the following lines


five admonition style labels:
NOTE
TIP
IMPORTANT
CAUTION
WARNING


Implicit literal text below:
 ~/secure/vault/defops
 


WARNING: "warning" is uppercase, followed by a colon (:), and an empty space


format style:
_italic phrase_
__i__talic le__tt__ers
*bold phrase*
**b**old le**tt**ers
*_bold italic phrase_*
**__b__**old italic le**__tt__**ers
`monospace phrase` and le``tt``ers
`_monospace italic phrase_` and le``__tt__``ers
`*monospace bold phrase*` and le``**tt**``ers
`*_monospace bold italic phrase_*` and le``**__tt__**``ers



\*Stars* will appear as *Stars*, not as bold text.
\&sect; will appear as an entity reference, not the &sect; symbol.
\\__func__ will appear as __func__, not as emphasized text.
\{two-semicolons} will appear {two-semicolons}, not resolved as ;;.


The markup pass:[<u>underline me</u>] renders as underlined text.



